### ISSUE TITLE
ERROR: c:/users/mypath/sld-tree-generator-master/extern/download.pl:46:

### ISSUE THREAD

**Issue by std044691** [apoll500/sld-tree-generator#1]
I get the following error:

C:\Users\themhz\Documents\Prolog\sld-tree-generator-master>swipl sld.pl
downloading https://raw.githubusercontent.com/processing-js/processing-js/v1.4.8/processing.js ...
ERROR: c:/users/themhz/documents/prolog/sld-tree-generator-master/extern/download.pl:46:
ERROR:    open/4: source_sink `'extern/processing/processing.js'' does not exist (No such file or directory)
Warning: c:/users/themhz/documents/prolog/sld-tree-generator-master/extern/download.pl:46:
Warning:    Goal (directive) failed: user:download
Welcome to SWI-Prolog (threaded, 64 bits, version 8.2.1)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

1 ?-

however i can run start. and i get

1 ?- start.
% Started server at http://localhost:5000/
% SWI-Prolog http server started.
% Please open http://localhost:5000/sld/ in your favourite browser.
true.

but the link at http://localhost:5000/sld/ works but I am stuck in the loading screen. 
Can anyone help?

**Comment by std044691** [comment]
![image](https://user-images.githubusercontent.com/60867100/101054840-ff9de500-3591-11eb-98dc-8ee92911bbb4.png)

**Comment by apoll500** [comment]
There should be an empty folder `extern/processing/`, which is missing in the repository.
If you create this folder manually, it should work.

**Comment by apoll500** [comment]
The folder has been added now.

**Comment by std044691** [comment]
yes it ok now. I need to mention that I needed to run the installation again. Great project thank you
